name: Catapitana Environment

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
      - name: Say hello!
        run: echo Hello from Catapitana Organization!

  env-variable:
    needs: hello
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Use environment variable
        run: echo ${{ vars.DEV_VARIABLE }}
